### ISSUE TITLE
oceanographic sensors on instrument?

### ISSUE THREAD

**Issue by jdpye** [ocean-tracking-network/biologging_standardization#3]
Noticing a few obvious places in the sensorML template to talk about the oceanographic capabilities of the instrument (no surprise, that's what it's made to do), but I'm having trouble getting details about any oceanographic capability from the metadata itself. Anywhere I should be looking?

**Comment by camrinbraun** [comment]
Can you clarify the question here @jdpye ? Not sure i understand exactly what you're after

**Comment by jdpye** [comment]
Sure, like if there's a pressure sensor, how often does it sample, what do we know about it specifically. If we don't have anything we won't have anything to put in, but do we know parameters of the thermister, pressure, light sensors themselves?

**Comment by camrinbraun** [comment]
for sure there are specs associated with resolution, accuracy, sampling rate, etc. such as [here](https://wildlifecomputers.com/our-tags/pop-up-satellite-tags-fish/minipat/)

**Comment by jdpye** [comment]
OK, cool, they don't give out anything different from what's on the brochure on purchase? Any specifics of factory calibration? I'm gonna put especial focus on things that a manufacturer might wanna tell a user about the gear that was just bought that would be specific to that individual instrument, with an eye toward making good suggestions for the SMRU gang when they are looking to codify some of their configurations.

**Comment by camrinbraun** [comment]
I know at least WC has internal spec sheets on individual sensors such as from when they do calibration. For example, they characterize a light sensor before shipping the tag, run the tag through some temperature/pressure cycling to check it, etc. These spec sheets for the tags/sensors exist but aren't typically provided with a tag order unless specifically requested.

**Comment by jdpye** [comment]
Ah, darn. OK, i'll try and just leave a placeholder for them, it'll help with general data re-usability by other groups if we can get em to include the cals in this format.
