### ISSUE TITLE
missing field

### ISSUE THREAD

**Issue by camrinbraun** [ocean-tracking-network/biologging_standardization#8]
ownerPhoneContact missing from templates (broken [link](https://github.com/ocean-tracking-network/biologging_standardization/blob/master/templates/fields/ownerPhoneContact.md)) but present in [deployment-metadata](https://github.com/ocean-tracking-network/biologging_standardization/blob/master/templates/deployment-metadata.md)

**Comment by lauramcdonnell** [comment]
I added ownerPhoneContact to fields - should link now!
